from io import BytesIO
from google.cloud import storage
import tensorflow as tf
import numpy as np

model = None
class_names = ["Aloevera", "Amla", "Amruthaballi", "Arali", "Astma_weed", "Badipala", "Balloon_Vine", "Bamboo", "Beans", "Betel",
            "Bhrami", "Bringaraja", "Caricature", "Castor", "Catharanthus", "Chakte", "Chilly", "Citron lime (herelikai)",
            "Coffee", "Common rue(naagdalli)", "Coriender", "Curry", "Doddpathre", "Drumstick", "Ekka", "Eucalyptus",
            "Ganigale", "Ganike", "Gasagase", "Ginger", "Globe Amarnath", "Guava", "Henna", "Hibiscus", "Honge", "Insulin",
            "Jackfruit", "Jasmine", "Kambajala", "Kasambruga", "Kohlrabi", "Lantana", "Lemon", "Lemongrass", "Malabar_Nut",
            "Malabar_Spinach", "Mango", "Marigold", "Mint", "Neem", "Nelavembu", "Nerale", "Nooni", "Onion", "Padri",
            "Palak(Spinach)", "Papaya", "Parijatha", "Pea", "Pepper", "Pomoegranate", "Pumpkin", "Raddish", "Rose",
            "Sampige", "Sapota", "Seethaashoka", "Seethapala", "Spinach1", "Tamarind", "Taro", "Tecoma", "Thumbe", "Tomato",
            "Tulsi", "Turmeric", "ashoka", "camphor", "kamakasturi", "kepala"]

medicinal_uses = {
    "Aloevera": ["Aloe vera is known for its healing properties, particularly for treating burns and wounds.",
                 "It also has anti-inflammatory effects and is used in various skincare products."],
    "Amla": ["Amla, also known as Indian gooseberry, is rich in vitamin C and antioxidants.",
             "It is used in Ayurvedic medicine to boost immunity, improve digestion, and promote hair health."],
    "Amruthaballi": ["Amruthaballi, or Giloy, is known for its immunomodulatory properties.",
                     "It is used in Ayurveda to boost immunity, treat fever, and improve digestion."],
    "Arali": ["The Arali plant has been used in traditional medicine to treat respiratory ailments.",
              "It is also believed to have anti-inflammatory and pain-relieving properties."],
    "Astma_weed": ["Asthma weed, also known as Euphorbia hirta, is used traditionally to treat respiratory conditions such as asthma and bronchitis.",
                   "It is also used to relieve cough and alleviate symptoms of colds and flu."],
    "Badipala": ["Badipala, or Bael, is used in Ayurvedic medicine to treat digestive disorders such as diarrhea and dysentery.",
                 "It is also believed to have anti-inflammatory and antimicrobial properties."],
    "Balloon_Vine": ["Balloon vine, also known as Cardiospermum halicacabum, has been used traditionally to treat skin conditions such as eczema and psoriasis.",
                     "It is also used to relieve inflammation and pain associated with arthritis."],
    "Bamboo": ["Bamboo shoots are rich in fiber, vitamins, and minerals.",
               "They are used in traditional medicine to improve digestion, promote weight loss, and strengthen the immune system."],
    "Beans": ["Beans are a good source of protein, fiber, vitamins, and minerals.",
              "They are used in traditional medicine to lower cholesterol levels, regulate blood sugar, and promote heart health."],
    "Betel": ["Betel leaves are chewed as a stimulant and are believed to aid digestion.",
              "They are also used in traditional medicine to relieve cough, sore throat, and other respiratory conditions."],
    "Bhrami": ["Brahmi, also known as Bacopa monnieri, is used in Ayurvedic medicine to improve cognitive function and memory.",
               "It is also believed to have antidepressant and anxiolytic properties."],
    "Bringaraja": ["Bringaraja, also known as Eclipta prostrata, is used in Ayurvedic medicine to promote hair growth and prevent hair loss.",
                   "It is also used to improve liver function and treat liver disorders."],
    "Caricature": ["The Caricature plant, also known as Graptophyllum pictum, is used in traditional medicine to treat skin conditions such as eczema and dermatitis.",
                   "It is also believed to have anti-inflammatory and analgesic properties."],
    "Castor": ["Castor oil, extracted from the seeds of the Castor plant, is used topically to relieve constipation and stimulate labor during childbirth.",
               "It is also used in traditional medicine to promote wound healing and reduce inflammation."],
    "Catharanthus": ["Catharanthus, also known as Madagascar periwinkle, is used in traditional medicine to treat diabetes and high blood pressure.",
                     "It is also used to relieve symptoms of malaria and other fevers."],
    "Chakte": ["Chakte, or Caesalpinia platyloba, is used in traditional medicine to treat inflammation, pain, and gastrointestinal disorders.",
               "It is also believed to have antimicrobial and antioxidant properties."],
    "Chilly": ["Chili peppers are rich in capsaicin, which has been shown to have pain-relieving and anti-inflammatory properties.",
               "They are also believed to boost metabolism and promote weight loss."],
    "Citron lime (herelikai)": ["Citron lime, also known as Herelikai, is rich in vitamin C and antioxidants.",
                                  "It is used in traditional medicine to boost immunity, aid digestion, and promote skin health."],
    "Coffee": ["Coffee contains caffeine, which has stimulant properties and can improve mental alertness and concentration.",
               "It is also believed to have antioxidant properties and may reduce the risk of certain diseases."],
    "Common rue(naagdalli)": ["Common rue, also known as Ruta graveolens, is used in traditional medicine to treat digestive disorders such as indigestion and flatulence.",
                               "It is also used to relieve menstrual cramps and promote menstruation."],
    "Coriender": ["Coriander leaves, also known as cilantro, are rich in vitamins, minerals, and antioxidants.",
                  "They are used in traditional medicine to aid digestion, reduce inflammation, and lower cholesterol levels."],
    "Curry": ["Curry leaves are rich in antioxidants and have anti-inflammatory properties.",
              "They are used in traditional medicine to aid digestion, lower blood sugar levels, and promote heart health."],
    "Doddpathre": ["Doddapatre, or Indian borage, is used in traditional medicine to treat respiratory conditions such as asthma and bronchitis.",
                   "It is also used to relieve cough, sore throat, and fever."],
    "Drumstick": ["Drumstick leaves, also known as Moringa leaves, are rich in vitamins, minerals, and antioxidants.",
                   "They are used in traditional medicine to boost immunity, promote digestion, and reduce inflammation."],
    "Ekka": ["Ekka, or Cajanus cajan, is used in traditional medicine to treat respiratory conditions such as cough, cold, and asthma.",
             "It is also used to promote wound healing and reduce inflammation."],
    "Eucalyptus": ["Eucalyptus leaves contain eucalyptol, which has antiseptic and decongestant properties.",
                    "They are used in traditional medicine to treat respiratory conditions such as cough, cold, and bronchitis."],
    "Ganigale": ["Ganigale, or Piper betle, is chewed as a stimulant and breath freshener.",
                 "It is also used in traditional medicine to treat digestive disorders such as indigestion and flatulence."],
    "Ganike": ["Ganike, or Piper nigrum, is used as a spice and has been used in traditional medicine to aid digestion and promote gastrointestinal health.",
               "It is also believed to have antioxidant and antimicrobial properties."],
    "Gasagase": ["Gasagase, or poppy seeds, are rich in healthy fats, protein, and fiber.",
                 "They are used in traditional medicine to relieve constipation, promote sleep, and reduce anxiety."],
    "Ginger": ["Ginger contains bioactive compounds such as gingerol, which have anti-inflammatory and antioxidant properties.",
               "It is used in traditional medicine to treat nausea, indigestion, and menstrual cramps."],
    "Globe Amarnath": ["Globe amaranth, also known as Gomphrena globosa, is used in traditional medicine to treat skin conditions such as acne and eczema.",
                        "It is also used to relieve inflammation and pain associated with arthritis."],
    "Guava": ["Guava leaves are rich in antioxidants and have anti-inflammatory properties.",
              "They are used in traditional medicine to treat diarrhea, reduce blood sugar levels, and promote heart health."],
    "Henna": ["Henna leaves are used to make a natural dye that is applied to the skin and hair.",
              "They are also used in traditional medicine to treat skin conditions such as eczema, psoriasis, and fungal infections."],
    "Hibiscus": ["Hibiscus flowers are rich in antioxidants and have anti-inflammatory properties.",
                 "They are used in traditional medicine to lower blood pressure, promote weight loss, and improve liver health."],
    "Honge": ["Honge leaves, also known as Pongamia pinnata, are used in traditional medicine to treat skin conditions such as eczema and psoriasis.",
              "They are also used to relieve inflammation and pain associated with arthritis."],
    "Insulin": ["Insulin plant, also known as Costus igneus, is used in traditional medicine to lower blood sugar levels in diabetic patients.",
                "It is also believed to have anti-inflammatory and antioxidant properties."],
    "Jackfruit": ["Jackfruit leaves are used in traditional medicine to treat wounds, skin infections, and insect bites.",
                  "They are also believed to have anti-inflammatory and antimicrobial properties."],
    "Jasmine": ["Jasmine flowers are used in traditional medicine to treat headaches, insomnia, and anxiety.",
                "They are also used to promote relaxation and improve mood."],
    "Kambajala": ["Kambajala, or Lantana camara, is used in traditional medicine to treat skin conditions such as eczema, psoriasis, and fungal infections.",
                  "It is also used to relieve inflammation and pain associated with arthritis."],
    "Kasambruga": ["Kasambruga, or Cinnamomum tamala, is used in traditional medicine to treat respiratory conditions such as cough, cold, and asthma.",
                    "It is also used to relieve digestive disorders such as indigestion and flatulence."],
    "Kohlrabi": ["Kohlrabi leaves are rich in vitamins, minerals, and antioxidants.",
                 "They are used in traditional medicine to boost immunity, aid digestion, and promote heart health."],
    "Lantana": ["Lantana leaves, also known as Kambajala, are used in traditional medicine to treat skin conditions such as eczema and psoriasis.",
                "They are also used to relieve inflammation and pain associated with arthritis."],
    "Lemon": ["Lemon leaves are rich in antioxidants and have anti-inflammatory properties.",
              "They are used in traditional medicine to treat digestive disorders, promote weight loss, and improve skin health."],
    "Lemongrass": ["Lemongrass contains citral, which has antimicrobial and anti-inflammatory properties.",
                   "It is used in traditional medicine to treat digestive disorders, relieve anxiety, and promote relaxation."],
    "Malabar_Nut": ["Malabar nut, also known as Justicia adhatoda, is used in traditional medicine to treat respiratory conditions such as asthma and bronchitis.",
                     "It is also used to relieve cough, sore throat, and fever."],
    "Malabar_Spinach": ["Malabar spinach leaves are rich in vitamins, minerals, and antioxidants.",
                         "They are used in traditional medicine to boost immunity, aid digestion, and promote heart health."],
    "Mango": ["Mango leaves are used in traditional medicine to treat diabetes, lower blood pressure, and promote heart health.",
               "They are also believed to have anti-inflammatory and antioxidant properties."],
    "Marigold": ["Marigold flowers are used in traditional medicine to treat skin conditions such as cuts, burns, and insect bites.",
                 "They are also used to relieve inflammation and pain associated with arthritis."],
    "Mint": ["Mint leaves contain menthol, which has cooling and soothing properties.",
             "They are used in traditional medicine to treat indigestion, relieve headaches, and promote relaxation."],
    "Neem": ["Neem leaves are rich in antioxidants and have antibacterial and antifungal properties.",
             "They are used in traditional medicine to treat skin conditions such as acne, eczema, and psoriasis."],
    "Nelavembu": ["Nelavembu, or Andrographis paniculata, is used in traditional medicine to boost immunity, reduce fever, and treat infections.",
                   "It is also used to relieve symptoms of colds, flu, and respiratory conditions."],
    "Nerale": ["Nerale, or Jamun, is used in traditional medicine to treat diabetes, lower blood pressure, and promote heart health.",
               "It is also believed to have anti-inflammatory and antioxidant properties."],
    "Nooni": ["Nooni, or Tamarillo, is rich in vitamins, minerals, and antioxidants.",
              "It is used in traditional medicine to boost immunity, aid digestion, and promote heart health."],
    "Onion": ["Onion has antimicrobial and anti-inflammatory properties.",
              "It is used in traditional medicine to treat cough, cold, sore throat, and other respiratory conditions."],
    "Padri": ["Padri, or Centella asiatica, is used in traditional medicine to improve cognitive function and memory.",
              "It is also believed to have anti-anxiety and antidepressant properties."],
    "Palak(Spinach)": ["Spinach leaves are rich in vitamins, minerals, and antioxidants.",
                        "They are used in traditional medicine to boost immunity, aid digestion, and promote heart health."],
    "Papaya": ["Papaya leaves are used in traditional medicine to treat dengue fever and other viral infections.",
               "They are also used to promote digestion and relieve digestive disorders such as constipation."],
    "Parijatha": ["Parijatha, or Night Jasmine, is used in traditional medicine to treat fever, headache, and joint pain.",
                   "It is also used to relieve stress, anxiety, and insomnia."],
    "Pea": ["Pea leaves are rich in protein, fiber, vitamins, and minerals.",
            "They are used in traditional medicine to promote heart health, aid digestion, and regulate blood sugar levels."],
    "Pepper": ["Pepper contains piperine, which has antioxidant and anti-inflammatory properties.",
               "It is used in traditional medicine to aid digestion, relieve cough, cold, and congestion."],
    "Pomoegranate": ["Pomegranate leaves are rich in antioxidants and have anti-inflammatory properties.",
                     "They are used in traditional medicine to treat diarrhea, lower blood pressure, and promote heart health."],
    "Pumpkin": ["Pumpkin leaves are rich in vitamins, minerals, and antioxidants.",
                "They are used in traditional medicine to boost immunity, aid digestion, and promote heart health."],
    "Raddish": ["Radish leaves are rich in vitamins, minerals, and antioxidants.",
                "They are used in traditional medicine to boost immunity, aid digestion, and promote heart health."],
    "Rose": ["Rose petals are used in traditional medicine to treat skin conditions such as acne, eczema, and psoriasis.",
             "They are also used to relieve stress, anxiety, and depression."],
    "Sampige": ["Sampige, or Jasmine, is used in traditional medicine to treat headaches, insomnia, and anxiety.",
                "It is also used to promote relaxation and improve mood."],
    "Sapota": ["Sapota leaves are used in traditional medicine to treat diarrhea, dysentery, and other gastrointestinal disorders.",
               "They are also used to relieve pain and inflammation associated with arthritis."],
    "Seethaashoka": ["Seethaashoka, or Saraca indica, is used in traditional medicine to treat gynecological disorders such as menstrual irregularities and menopausal symptoms.",
                       "It is also used to relieve pain and inflammation associated with arthritis."],
    "Seethapala": ["Seethapala, or Custard apple, is used in traditional medicine to treat digestive disorders such as indigestion, flatulence, and constipation.",
                     "It is also used to relieve cough, sore throat, and fever."],
    "Spinach1": ["Spinach leaves are rich in vitamins, minerals, and antioxidants.",
                 "They are used in traditional medicine to boost immunity, aid digestion, and promote heart health."],
    "Tamarind": ["Tamarind leaves are used in traditional medicine to treat digestive disorders such as indigestion, flatulence, and constipation.",
                  "They are also used to relieve cough, sore throat, and fever."],
    "Taro": ["Taro leaves are rich in vitamins, minerals, and antioxidants.",
             "They are used in traditional medicine to boost immunity, aid digestion, and promote heart health."],
    "Tecoma": ["Tecoma leaves, also known as Trumpet creeper, are used in traditional medicine to treat respiratory conditions such as asthma and bronchitis.",
                "They are also used to relieve cough, sore throat, and fever."],
    "Thumbe": ["Thumbe, or Leucas aspera, is used in traditional medicine to treat respiratory conditions such as cough, cold, and asthma.",
                "It is also used to relieve digestive disorders such as indigestion and flatulence."],
    "Tomato": ["Tomato leaves contain solanine, which has been used in traditional medicine to treat arthritis, inflammation, and pain.",
               "They are also used to promote heart health, aid digestion, and boost immunity."],
    "Tulsi": ["Tulsi, or Holy Basil, is used in traditional medicine to boost immunity, promote respiratory health, and reduce stress.",
              "It is also used to treat cough, cold, fever, and other respiratory conditions."],
    "Turmeric": ["Turmeric contains curcumin, which has anti-inflammatory and antioxidant properties.",
                 "It is used in traditional medicine to treat arthritis, digestive disorders, and skin conditions."],
    "ashoka": ["Ashoka leaves, also known as Saraca indica, are used in traditional medicine to treat gynecological disorders such as menstrual irregularities and menopausal symptoms.",
                "They are also used to relieve pain and inflammation associated with arthritis."],
    "camphor": ["Camphor is used topically to relieve pain and itching associated with insect bites, minor burns, and skin irritation.",
                "It is also used in aromatherapy to promote relaxation and relieve respiratory congestion."],
    "kamakasturi": ["Kamakasturi, or Mallotus philippensis, is used in traditional medicine to treat skin conditions such as eczema, psoriasis, and fungal infections.",
                      "It is also used to relieve inflammation and pain associated with arthritis."],
    "kepala": ["Kepala, or Capsicum annuum, is used in traditional medicine to treat digestive disorders such as indigestion, flatulence, and constipation.",
                "It is also used to relieve cough, sore throat, and fever."]
}

plant_links = {
    "Aloevera": "https://en.wikipedia.org/wiki/Aloe_vera",
    "Amla": "https://en.wikipedia.org/wiki/Phyllanthus_emblica",
    "Amruthaballi": "https://en.wikipedia.org/wiki/Centella_asiatica",
    "Arali": "https://en.wikipedia.org/wiki/Ficus_racemosa",
    "Astma_weed": "https://en.wikipedia.org/wiki/Euphorbia_hirta",
    "Badipala": "https://en.wikipedia.org/wiki/Indigofera_linnaei",
    "Balloon_Vine": "https://en.wikipedia.org/wiki/Cardiospermum_halicacabum",
    "Bamboo": "https://en.wikipedia.org/wiki/Bamboo",
    "Beans": "https://en.wikipedia.org/wiki/Phaseolus_vulgaris",
    "Betel": "https://en.wikipedia.org/wiki/Piper_betle",
    "Bhrami": "https://en.wikipedia.org/wiki/Bacopa_monnieri",
    "Bringaraja": "https://en.wikipedia.org/wiki/Eclipta_prostrata",
    "Caricature": "https://en.wikipedia.org/wiki/Graptophyllum_pictum",
    "Castor": "https://en.wikipedia.org/wiki/Ricinus",
    "Catharanthus": "https://en.wikipedia.org/wiki/Catharanthus_roseus",
    "Chakte": "https://en.wikipedia.org/wiki/Haematoxylum_campechianum",
    "Chilly": "https://en.wikipedia.org/wiki/Chili_pepper",
    "Citron lime (herelikai)": "https://en.wikipedia.org/wiki/Buddha%27s_hand",
    "Coffee": "https://en.wikipedia.org/wiki/Coffea",
    "Common rue(naagdalli)": "https://en.wikipedia.org/wiki/Ruta_graveolens",
    "Coriender": "https://en.wikipedia.org/wiki/Coriander",
    "Curry": "https://en.wikipedia.org/wiki/Curry_tree",
    "Doddpathre": "https://en.wikipedia.org/wiki/Plectranthus_amboinicus",
    "Drumstick": "https://en.wikipedia.org/wiki/Moringa_oleifera",
    "Ekka": "https://en.wikipedia.org/wiki/Calotropis_gigantea",
    "Eucalyptus": "https://en.wikipedia.org/wiki/Eucalyptus",
    "Ganigale": "https://en.wikipedia.org/wiki/Desmodium_gangeticum",
    "Ganike": "https://en.wikipedia.org/wiki/Eclipta_prostrata",
    "Gasagase": "https://en.wikipedia.org/wiki/Opium_poppy",
    "Ginger": "https://en.wikipedia.org/wiki/Ginger",
    "Globe Amarnath": "https://en.wikipedia.org/wiki/Amaranthus_gangeticus",
    "Guava": "https://en.wikipedia.org/wiki/Psidium_guajava",
    "Henna": "https://en.wikipedia.org/wiki/Henna",
    "Hibiscus": "https://en.wikipedia.org/wiki/Hibiscus",
    "Honge": "https://en.wikipedia.org/wiki/Pongamia_pinnata",
    "Insulin": "https://en.wikipedia.org/wiki/Gymnema_sylvestre",
    "Jackfruit": "https://en.wikipedia.org/wiki/Jackfruit",
    "Jasmine": "https://en.wikipedia.org/wiki/Jasmine",
    "Kambajala": "https://en.wikipedia.org/wiki/Piper_chaba",
    "Kasambruga": "https://en.wikipedia.org/wiki/Brugmansia",
    "Kohlrabi": "https://en.wikipedia.org/wiki/Kohlrabi",
    "Lantana": "https://en.wikipedia.org/wiki/Lantana",
    "Lemon": "https://en.wikipedia.org/wiki/Lemon",
    "Lemongrass": "https://en.wikipedia.org/wiki/Cymbopogon",
    "Malabar_Nut": "https://en.wikipedia.org/wiki/Justicia_adhatoda",
    "Malabar_Spinach": "https://en.wikipedia.org/wiki/Basella_alba",
    "Mango": "https://en.wikipedia.org/wiki/Mango",
    "Marigold": "https://en.wikipedia.org/wiki/Marigold",
    "Mint": "https://en.wikipedia.org/wiki/Mentha",
    "Neem": "https://en.wikipedia.org/wiki/Neem",
    "Nelavembu": "https://en.wikipedia.org/wiki/Andrographis_paniculata",
    "Nerale": "https://en.wikipedia.org/wiki/Sesbania_grandiflora",
    "Nooni": "https://en.wikipedia.org/wiki/Ardisia_humilis",
    "Onion": "https://en.wikipedia.org/wiki/Onion",
    "Padri": "https://en.wikipedia.org/wiki/Cissus_quadrangularis",
    "Palak(Spinach)": "https://en.wikipedia.org/wiki/Spinacia_oleracea",
    "Papaya": "https://en.wikipedia.org/wiki/Carica_papaya",
    "Parijatha": "https://en.wikipedia.org/wiki/Nyctanthes_arbor-tristis",
    "Pea": "https://en.wikipedia.org/wiki/Pea",
    "Pepper": "https://en.wikipedia.org/wiki/Black_pepper",
    "Pomoegranate": "https://en.wikipedia.org/wiki/Pomegranate",
    "Pumpkin": "https://en.wikipedia.org/wiki/Pumpkin",
    "Raddish": "https://en.wikipedia.org/wiki/Raphanus_sativus",
    "Rose": "https://en.wikipedia.org/wiki/Rose",
    "Sampige": "https://en.wikipedia.org/wiki/Plumeria",
    "Sapota": "https://en.wikipedia.org/wiki/Manilkara_zapota",
    "Seethaashoka": "https://en.wikipedia.org/wiki/Saraca_asoca",
    "Seethapala": "https://en.wikipedia.org/wiki/Citrus_sinensis",
    "Spinach1": "https://en.wikipedia.org/wiki/Spinach",
    "Tamarind": "https://en.wikipedia.org/wiki/Tamarind",
    "Taro": "https://en.wikipedia.org/wiki/Taro",
    "Tecoma": "https://en.wikipedia.org/wiki/Tecoma",
    "Thumbe": "https://en.wikipedia.org/wiki/Solanum_trilobatum",
    "Tomato": "https://en.wikipedia.org/wiki/Solanum_lycopersicum",
    "Tulsi": "https://en.wikipedia.org/wiki/Ocimum_tenuiflorum",
    "Turmeric": "https://en.wikipedia.org/wiki/Curcuma_longa",
    "ashoka": "https://en.wikipedia.org/wiki/Saraca_asoca",
    "camphor": "https://en.wikipedia.org/wiki/Cinnamomum_camphora",
    "kamakasturi": "https://en.wikipedia.org/wiki/Abelmoschus_moschatus",
    "kepala": "https://en.wikipedia.org/wiki/Cinnamomum_camphora",
    "Sesbania grandiflora": "https://en.wikipedia.org/wiki/Sesbania_grandiflora",
    "Tulsi": "https://en.wikipedia.org/wiki/Ocimum_tenuiflorum",
    "Tecoma": "https://en.wikipedia.org/wiki/Tecoma",
    "Thumbe": "https://en.wikipedia.org/wiki/Solanum_trilobatum",
    "Tomato": "https://en.wikipedia.org/wiki/Solanum_lycopersicum",
    "Tulsi": "https://en.wikipedia.org/wiki/Ocimum_tenuiflorum",
    "Turmeric": "https://en.wikipedia.org/wiki/Curcuma_longa",
    "ashoka": "https://en.wikipedia.org/wiki/Saraca_asoca",
    "camphor": "https://en.wikipedia.org/wiki/Cinnamomum_camphora",
    "kamakasturi": "https://en.wikipedia.org/wiki/Abelmoschus_moschatus",
    "kepala": "https://en.wikipedia.org/wiki/Cinnamomum_camphora"
}



BUCKET_NAME = "med_leaf_model" # Here you need to put the name of your GCP bucket


def download_blob(bucket_name, source_blob_name, destination_file_name):
    """Downloads a blob from the bucket."""
    storage_client = storage.Client()
    bucket = storage_client.get_bucket(bucket_name)
    blob = bucket.blob(source_blob_name)

    blob.download_to_filename(destination_file_name)

    print(f"Blob {source_blob_name} downloaded to {destination_file_name}.")


def predict(request):
    global model
    if model is None:
        download_blob(
            BUCKET_NAME,
            "models/leaf.h5",
            "/tmp/leaf.h5",
        )
        model = tf.keras.models.load_model("/tmp/leaf.h5")

    image = request.files["file"]

    # Convert FileStorage object to bytes
    image_bytes = image.read()

    # Load the image from bytes using BytesIO
    img = tf.keras.preprocessing.image.load_img(BytesIO(image_bytes), target_size=(299, 299))
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)  # Create a batch

    # Make predictions
    predictions = model.predict(img_array)
    score = tf.nn.sigmoid(predictions[0])
    description = medicinal_uses[class_names[np.argmax(score)]]
    plant_link = plant_links[class_names[np.argmax(score)]]
   
    return {"class": class_names[np.argmax(score)], "confidence": 100 * np.max(score),"description": description, "plantlink": plant_link}
